
EVENTSTR_COMMAND:=
EVENTSTR_COMMAND+='$$KAFKA_BROKERS_9092_1,$$KAFKA_BROKERS_9092_2,$$KAFKA_BROKERS_9092_3,$$ZK_BROKERS_2181_1,$$ZK_BROKERS_2181_2,$$ZK_BROKERS_2181_3' 
EVENTSTR_COMMAND+= < ./tmpl/burrow.toml
EVENTSTR_COMMAND+=  | tee burrow.toml

bootstrap:
	envsubst ${EVENTSTR_COMMAND} 
	docker compose up -d