
ENVSUBST_COMMAND_ARGS:=
ENVSUBST_COMMAND_ARGS+='$$KAFKA_BROKERS_9092_1,$$KAFKA_BROKERS_9092_2,$$KAFKA_BROKERS_9092_3,$$ZK_BROKERS_2181_1,$$ZK_BROKERS_2181_2,$$ZK_BROKERS_2181_3'
ENVSUBST_COMMAND_ARGS+= < ./tmpl/burrow.toml
ENVSUBST_COMMAND_ARGS+=  | tee burrow.toml

bootstrap:
	envsubst ${ENVSUBST_COMMAND_ARGS}
	docker compose up -d